/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uaslabpbo1;

import javax.swing.JOptionPane;

/**
 *
 * @author fransisca
 */
public class TambahMenuForm extends javax.swing.JFrame {
    int totalBelanja = 1;
    public TambahMenuForm() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        btn_kentang = new javax.swing.JToggleButton();
        label_menu1 = new javax.swing.JLabel();
        label_harga1 = new javax.swing.JLabel();
        btn_bigmoc = new javax.swing.JToggleButton();
        label_menu2 = new javax.swing.JLabel();
        label_harga2 = new javax.swing.JLabel();
        btn_pamer = new javax.swing.JToggleButton();
        label_menu6 = new javax.swing.JLabel();
        label_harga6 = new javax.swing.JLabel();
        btn_nugget = new javax.swing.JToggleButton();
        label_menu3 = new javax.swing.JLabel();
        label_harga3 = new javax.swing.JLabel();
        label_harga5 = new javax.swing.JLabel();
        btn_kopi = new javax.swing.JToggleButton();
        btn_ayam = new javax.swing.JToggleButton();
        btn_sundae = new javax.swing.JToggleButton();
        btn_leci = new javax.swing.JToggleButton();
        btn_cola = new javax.swing.JSeparator();
        label_menu5 = new javax.swing.JLabel();
        btn_coke = new javax.swing.JToggleButton();
        label_harga4 = new javax.swing.JLabel();
        label_menu4 = new javax.swing.JLabel();
        label_menu7 = new javax.swing.JLabel();
        label_harga7 = new javax.swing.JLabel();
        label_menu8 = new javax.swing.JLabel();
        label_harga8 = new javax.swing.JLabel();
        label_menu9 = new javax.swing.JLabel();
        label_harga9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_kentang.setForeground(new java.awt.Color(255, 255, 255));
        btn_kentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Kentang goyeng.png"))); // NOI18N
        btn_kentang.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 206, 4), 2, true));
        btn_kentang.setContentAreaFilled(false);
        btn_kentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kentangActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 90, 80));

        label_menu1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_menu1.setText("Kentang Goreng");
        getContentPane().add(label_menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        label_harga1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_harga1.setText("Rp 19.000");
        getContentPane().add(label_harga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        btn_bigmoc.setForeground(new java.awt.Color(255, 255, 255));
        btn_bigmoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Bigmac.png"))); // NOI18N
        btn_bigmoc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 206, 4), 2, true));
        btn_bigmoc.setContentAreaFilled(false);
        btn_bigmoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bigmocActionPerformed(evt);
            }
        });
        getContentPane().add(btn_bigmoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 340, -1, 80));

        label_menu2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_menu2.setText("PaMer 7 ");
        getContentPane().add(label_menu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        label_harga2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_harga2.setText("Rp 180.000");
        getContentPane().add(label_harga2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, -1, -1));

        btn_pamer.setForeground(new java.awt.Color(255, 255, 255));
        btn_pamer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paket orang kaya.png"))); // NOI18N
        btn_pamer.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 206, 4), 2, true));
        btn_pamer.setContentAreaFilled(false);
        btn_pamer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pamerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_pamer, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, 80));

        label_menu6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_menu6.setText("Mc Nuggets");
        getContentPane().add(label_menu6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 490, -1, -1));

        label_harga6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_harga6.setText("Rp 25.000");
        getContentPane().add(label_harga6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 520, -1, -1));

        btn_nugget.setForeground(new java.awt.Color(255, 255, 255));
        btn_nugget.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mcnuget.png"))); // NOI18N
        btn_nugget.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 206, 4), 2, true));
        btn_nugget.setContentAreaFilled(false);
        btn_nugget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuggetActionPerformed(evt);
            }
        });
        getContentPane().add(btn_nugget, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, -1, 70));

        label_menu3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_menu3.setText("Big Moc");
        getContentPane().add(label_menu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 360, -1, -1));

        label_harga3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_harga3.setText("Rp 41.000 ");
        getContentPane().add(label_harga3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 390, -1, -1));

        label_harga5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_harga5.setText("Rp 23.000");
        getContentPane().add(label_harga5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 520, -1, -1));

        btn_kopi.setForeground(new java.awt.Color(255, 255, 255));
        btn_kopi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kopio italiano.png"))); // NOI18N
        btn_kopi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 206, 4), 2, true));
        btn_kopi.setContentAreaFilled(false);
        btn_kopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kopiActionPerformed(evt);
            }
        });
        getContentPane().add(btn_kopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, -1, 80));

        btn_ayam.setForeground(new java.awt.Color(255, 255, 255));
        btn_ayam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/snack ayam gulung.png"))); // NOI18N
        btn_ayam.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 206, 4), 2, true));
        btn_ayam.setContentAreaFilled(false);
        btn_ayam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ayamActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ayam, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, -1, 80));

        btn_sundae.setForeground(new java.awt.Color(255, 255, 255));
        btn_sundae.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coklat sunda.png"))); // NOI18N
        btn_sundae.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 206, 4), 2, true));
        btn_sundae.setContentAreaFilled(false);
        btn_sundae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sundaeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sundae, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 470, -1, 80));

        btn_leci.setForeground(new java.awt.Color(255, 255, 255));
        btn_leci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/es teh leci.png"))); // NOI18N
        btn_leci.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 206, 4), 2, true));
        btn_leci.setContentAreaFilled(false);
        btn_leci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_leciActionPerformed(evt);
            }
        });
        getContentPane().add(btn_leci, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 620, -1, 80));

        btn_cola.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(btn_cola, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 1140, 0));

        label_menu5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_menu5.setText("Chicken Snack Wrap");
        getContentPane().add(label_menu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 200, -1));

        btn_coke.setForeground(new java.awt.Color(255, 255, 255));
        btn_coke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cola ori makudonarudo.png"))); // NOI18N
        btn_coke.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(253, 206, 4), 2, true));
        btn_coke.setContentAreaFilled(false);
        btn_coke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cokeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_coke, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 620, -1, 80));

        label_harga4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_harga4.setText("Rp 12.000");
        getContentPane().add(label_harga4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, -1));

        label_menu4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_menu4.setText("Sundae Chocolate");
        getContentPane().add(label_menu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 490, 160, -1));

        label_menu7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_menu7.setText("Coke McFloat");
        getContentPane().add(label_menu7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, -1, -1));

        label_harga7.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_harga7.setText("Rp 14.000");
        getContentPane().add(label_harga7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 670, -1, -1));

        label_menu8.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_menu8.setText("Iced Latte Frap");
        getContentPane().add(label_menu8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, -1, -1));

        label_harga8.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_harga8.setText("Rp 32.000");
        getContentPane().add(label_harga8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 670, -1, -1));

        label_menu9.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_menu9.setText("Iced Lychee Tea");
        getContentPane().add(label_menu9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 640, -1, -1));

        label_harga9.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        label_harga9.setText("Rp 20.000");
        getContentPane().add(label_harga9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 670, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Menu Tambah.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 950));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kentangActionPerformed
        String nama =   label_menu1.getText();
        String hargaString = label_harga1.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_kentangActionPerformed

    private void btn_pamerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pamerActionPerformed
        String nama =   label_menu2.getText();
        String hargaString = label_harga2.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_pamerActionPerformed

    private void btn_bigmocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bigmocActionPerformed
        String nama =   label_menu3.getText();
        String hargaString = label_harga3.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_bigmocActionPerformed

    private void btn_sundaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sundaeActionPerformed
        String nama =   label_menu4.getText();
        String hargaString = label_harga4.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_sundaeActionPerformed

    private void btn_ayamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ayamActionPerformed
         String nama =   label_menu5.getText();
        String hargaString = label_harga5.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_ayamActionPerformed

    private void btn_nuggetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuggetActionPerformed
        String nama =   label_menu6.getText();
        String hargaString = label_harga6.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_nuggetActionPerformed

    private void btn_cokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cokeActionPerformed
        String nama =   label_menu7.getText();
        String hargaString = label_harga7.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_cokeActionPerformed

    private void btn_kopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kopiActionPerformed
        String nama =   label_menu8.getText();
        String hargaString = label_harga8.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_kopiActionPerformed

    private void btn_leciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_leciActionPerformed
        String nama =   label_menu9.getText();
        String hargaString = label_harga9.getText();
        hargaString = hargaString.replaceAll("[^\\d.]", "");
        hargaString = hargaString.replace(".","");
        float hargaFloat = Float.parseFloat(hargaString);
  
        int jumlah = Integer.parseInt(JOptionPane.showInputDialog("Masukkan Jumlah Pesanan"));
        float jumlahFloat = (float) jumlah;
        
        float total = hargaFloat*jumlahFloat;
        
        DetailMenu.AddRowToJTable(new Object[]{
            totalBelanja++,
            nama,
            hargaFloat,
            jumlah,
            total       
       });
    }//GEN-LAST:event_btn_leciActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahMenuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahMenuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_ayam;
    private javax.swing.JToggleButton btn_bigmoc;
    private javax.swing.JToggleButton btn_coke;
    private javax.swing.JSeparator btn_cola;
    private javax.swing.JToggleButton btn_kentang;
    private javax.swing.JToggleButton btn_kopi;
    private javax.swing.JToggleButton btn_leci;
    private javax.swing.JToggleButton btn_nugget;
    private javax.swing.JToggleButton btn_pamer;
    private javax.swing.JToggleButton btn_sundae;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel label_harga1;
    private javax.swing.JLabel label_harga2;
    private javax.swing.JLabel label_harga3;
    private javax.swing.JLabel label_harga4;
    private javax.swing.JLabel label_harga5;
    private javax.swing.JLabel label_harga6;
    private javax.swing.JLabel label_harga7;
    private javax.swing.JLabel label_harga8;
    private javax.swing.JLabel label_harga9;
    private javax.swing.JLabel label_menu1;
    private javax.swing.JLabel label_menu2;
    private javax.swing.JLabel label_menu3;
    private javax.swing.JLabel label_menu4;
    private javax.swing.JLabel label_menu5;
    private javax.swing.JLabel label_menu6;
    private javax.swing.JLabel label_menu7;
    private javax.swing.JLabel label_menu8;
    private javax.swing.JLabel label_menu9;
    // End of variables declaration//GEN-END:variables
}
